### ISSUE TITLE
how to run it in Windows?

### ISSUE THREAD

**Issue by munge83** [petewarden/iPhoneTracker#10]
When I run te index.html it onely shows the mub al loading is yust spining and spining and spining , what to do ? Help !

**Comment by parkr** [comment]
This app is Mac only.

**Comment by parkr** [comment]
Sorry about your wasted time, but it's common knowledge that Objective-C is a language created for Mac Cocoa development.
You could take more of your time to go through your backups.

**Comment by parkr** [comment]
It's true. If I had the power, I would add them right now!

**Comment by hyperflux7** [comment]
Question - where do the files live on a Windows machine, and can Windows people not take the 'MobileSync' folder from their Win machine (assuming it has one) and then drop it into a replicated folder system in OSX to run the program?

**Comment by pbj** [comment]
I'm guessing C:\Users(user name)\AppData\Roaming\Apple Computer\SyncServices\Local\

**Comment by grhodes** [comment]
You can check the longitudes and latitudes on windows by doing the following:
1.  Download and run iphonebackupbrowser (http://code.google.com/p/iphonebackupbrowser/)
2.  When it opens select your backup from the drop down in the top left.
3.  Select the first entry in the top grid ("----                         System")
4.  Find the entry "Library/Caches/locationd/consolidated.db" and double click it.
5.  This will open up an explorer window with the file selected.
6.  Copy and paste this file to your documents and rename it with ".sqlite"
7.  Download and install the firefox plugin (https://addons.mozilla.org/en-US/firefox/addon/sqlite-manager/)
8.  Open the file you just copied to your documents
9.  Select the "CellLocation" table

Hope this helps

EDIT: found this application to do it for you (http://www.redcode.nl/blog/2011/04/reading-iphone-gps-data-from-backup-with-java/)

**Comment by pbj** [comment]
Rock and roll! Thanks!

**Comment by sandco** [comment]
Im prob stupid and not doing something properly. I have followed the 9 steps above and can now see the information.
How do I now export the SQL data into a mapping format? 
Thanks in advance.

**Comment by tmcw** [comment]
Here's a converter to shapefiles: https://gist.github.com/932879
(note: requires OGR library, isn't tested on Windows, isn't thoroughly tested)

**Comment by jamesbrowneuk** [comment]
Try this : http://www.iphonelocationtracker.co.uk/

**Comment by petewarden** [comment]
We haven't created a Windows version of the application ourselves. We have
seen quite a few versions by other people appear, that you should be able to
find by googling, but since we haven't checked them out personally it's hard
to vouch for any particular one. Sorry about that!

cheers,
           Pete

**Comment by jamesbrowneuk** [comment]
Not sure if anyone is still looking for a windows version, but I have updated my version a few times over the last few days.  It now uses both OpenHeatMap and GoogleMaps, will auto-detect the back ups that are on your PC and let you filter the visible data by start and end date.

http://www.iphonelocationtracker.co.uk/

**Comment by pbj** [comment]
Hi Jay. I'm getting an error:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
System.BadImageFormatException: Could not load file or assembly 'System.Data.SQLite, Version=1.0.66.0, Culture=neutral, PublicKeyToken=db937bc2d44ff139' or one of its dependencies. An attempt was made to load a program with an incorrect format.
File name: 'System.Data.SQLite, Version=1.0.66.0, Culture=neutral, PublicKeyToken=db937bc2d44ff139'
   at iPhoneLocationTracker.Form1.backupListBox_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ListBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ListBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog](DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5444 (Win7SP1GDR.050727-5400)

##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v2.0.50727/mscorlib.dll

iPhoneLocationTracker
    Assembly Version: 0.4.4131.29561
    Win32 Version: 0.4.*

##     CodeBase: file:///C:/Users/Peter/Desktop/iphone/_Downloads_iphonelocationtracker_v04/iPhoneLocationTracker.exe

System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)

##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)

##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)

##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System.Core
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.30729.5420 built by: Win7SP1

##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Core/3.5.0.0__b77a5c561934e089/System.Core.dll

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

I'm running Windows 7 - 64 bit and Version 4 of .NET

**Comment by jamesbrowneuk** [comment]
Hi pbj - thanks for the feedback.

Do you have the "System.Data.SQLite.dll" file located at the same level as the "iPhoneLocationTracker.exe" file ?  This is required, as SQLite is the format of the "consolidated.db" that hold the location data.

I am about to upload a new release, so will include the JIT part too :)

Let me know how you get on!

Thanks

James

**Comment by jamesbrowneuk** [comment]
pbj - how did you get on ?

As mentioned, I have just uploaded v0.5 - this now makes use of the "Horizontal Accuracy" data so that you can filter out the "bad" data.

http://www.iphonelocationtracker.co.uk/

Thanks

James

**Comment by wgongora** [comment]
Dear friend pbj & other fellow mates;

I was digging n googling around in order to make my app run properly. It couldn't load the DLL -- doesn't matter where i tried to place it. 

When I saw pbj's problem (exactly identical as mine), I noticed a small detail that didn't leave me any doubts of what was going wrong: we r both running a 64bit machine.

Assuming that I had a wrong version of the DLL, I went to http://system.data.sqlite.org/index.html/doc/trunk/www/downloads.wiki and downloaded its x64 version.

It would all be great IF it got to work after that, but still same shit is going on. I wonder if the app is still looking for a specific version of the DLL, and doesn't matter which one I get to install, it's still only gonna look towards the 32bit one?

Thanks in advance

**Comment by jamesbrowneuk** [comment]
hi wgongora - thanks for the feedback.

I will have a look into this and get back to you - hopefully with a fix!

Thanks

James

**Comment by wgongora** [comment]
Ah, a little question just in time; I dont honestly think that's the problem, once it specifically mentions the DLL file on the error message, but... ...do we must have a jailbroken backup set o files in order to have it all working?

My backup sets are all of a non-jailbroken iOS 4.2 version.

Thanks in advance for all ur support Jamie.

**Comment by jamesbrowneuk** [comment]
The issue IS the 64-bit processor - you don't need jailbroken backups to get this working.  The only other thing that will stop it working is if you choose to encrypt you backups - but the error your getting it becasue the SQLite dll is a 32-bit version.

I have created a test harness and got it working on both 32-bit and 64-bit - just need to update the main app and upload to the site - will post here once done.

**Comment by jamesbrowneuk** [comment]
Right done (that was easy - hopefully!).

I have uploaded a 64-bit version to the site : http://www.iphonelocationtracker.co.uk/Downloads.aspx

Please let me know how you get on!

**Comment by wgongora** [comment]
HOLY ****! YOU MADE IT!

Thanks a lot man.

**Comment by jamesbrowneuk** [comment]
Excellent! - Tell your friends / like the site on Facebook :)

**Comment by pbj** [comment]
Sorry for the delayed response James.

In response to your first question, yes, it was in the same folder.

I have downloaded the x64 version and I still get error messages. It's not the same as the x86 version though.
Screen shot: http://bit.ly/kpJRxs 
And my backups are NOT encrypted.

**Comment by jamesbrowneuk** [comment]
hi pbj - ok the issue is a locale issue with the dates - I will investigate and upload a fix.

**Comment by jamesbrowneuk** [comment]
Hi pbj - now updated and fixed in v0.6 : http://www.iphonelocationtracker.co.uk/Downloads.aspx

**Comment by pbj** [comment]
It works! OpenMap does not work though. It asks if I have flash player and then it says: blank?hasFlash=true&

I have absolutely no clue, but could this be a conflict due to no 64-bit version of flash?

**Comment by wgongora** [comment]
jaybee -- pbj's right. I'm also on 64bit, and OpenMap doesn't work at all --  It asks if I have flash player and then it says: blank?hasFlash=true& ....
